### ISSUE TITLE
Unknown error in dragon egg revival

### ISSUE THREAD

**Issue by Sodies** [2008Choco/DragonEggDrop#11] opened 2018-03-16 18:40 UTC
16.03 00:47:11 [Server] ERROR Cannot load plugins/DragonEggDrop/dragons/Haiku.yml 16.03 00:47:11 [Server] INFO org.bukkit.configuration.InvalidConfigurationException: while parsing a block collection 16.03 00:47:11 [Server] INFO in 'string', line 21, column 3: 16.03 00:47:11 [Server] INFO - "tellraw %player% {\"text\":\" ... 16.03 00:47:11 [Server] INFO ^ 16.03 00:47:11 [Server] INFO expected <block end>, but found FlowEntry 16.03 00:47:11 [Server] INFO in 'string', line 21, column 68: 16.03 00:47:11 [Server] INFO ... ongratulations! You have killed",\"color\":\"red\",\"extra\":[{\ ... 16.03 00:47:11 [Server] INFO ^ 16.03 00:47:11 [Server] INFO at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:55) ~[spigot-1.12.2.jar:git-Spigot-9f4c3d2-bd30843] 16.03 00:47:11 [Server] INFO at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:162) ~[spigot-1.12.2.jar:git-Spigot-9f4c3d2-bd30843] 16.03 00:47:11 [Server] INFO at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:130) ~[spigot-1.12.2.jar:git-Spigot-9f4c3d2-bd30843] 16.03 00:47:11 [Server] INFO at org.bukkit.configuration.file.YamlConfiguration.loadConfiguration(YamlConfiguration.java:178) [spigot-1.12.2.jar:git-Spigot-9f4c3d2-bd30843] 16.03 00:47:11 [Server] INFO at com.ninjaguild.dragoneggdrop.dragon.DragonTemplate.loadTemplates(DragonTemplate.java:477) [DragonEggDrop.jar:?] 16.03 00:47:11 [Server] INFO at com.ninjaguild.dragoneggdrop.management.DEDManager.reloadDragonTemplates(DEDManager.java:121) [DragonEggDrop.jar:?] 16.03 00:47:11 [Server] INFO at com.ninjaguild.dragoneggdrop.management.DEDManager.<init>(DEDManager.java:52) [DragonEggDrop.jar:?] 16.03 00:47:11 [Server] INFO at com.ninjaguild.dragoneggdrop.DragonEggDrop.onEnable(DragonEggDrop.java:135) [DragonEggDrop.jar:?] 16.03 00:47:11 [Server] INFO at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) [spigot-1.12.2.jar:git-Spigot-9f4c3d2-bd30843] 16.03 00:47:11 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337) [spigot-1.12.2.jar:git-Spigot-9f4c3d2-bd30843] 16.03 00:47:11 [Server] INFO at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:403) [spigot-1.12.2.jar:git-Spigot-9f4c3d2-bd30843] 16.03 00:47:11 [Server] INFO at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:381) [spigot-1.12.2.jar:git-Spigot-9f4c3d2-bd30843] 16.03 00:47:11 [Server] INFO at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:330) [spigot-1.12.2.jar:git-Spigot-9f4c3d2-bd30843] 16.03 00:47:11 [Server] INFO at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:422) [spigot-1.12.2.jar:git-Spigot-9f4c3d2-bd30843] 16.03 00:47:11 [Server] INFO at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:383) [spigot-1.12.2.jar:git-Spigot-9f4c3d2-bd30843] 16.03 00:47:11 [Server] INFO at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:338) [spigot-1.12.2.jar:git-Spigot-9f4c3d2-bd30843] 16.03 00:47:11 [Server] INFO at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:272) [spigot-1.12.2.jar:git-Spigot-9f4c3d2-bd30843] 16.03 00:47:11 [Server] INFO at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:545) [spigot-1.12.2.jar:git-Spigot-9f4c3d2-bd30843] 16.03 00:47:11 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131] 16.03 00:47:11 [Server] INFO Caused by: org.yaml.snakeyaml.parser.ParserException: while parsing a block collection 16.03 00:47:11 [Server] INFO in 'string', line 21, column 3: 16.03 00:47:11 [Server] INFO - "tellraw %player% {\"text\":\" ... 16.03 00:47:11 [Server] INFO ^ 16.03 00:47:11 [Server] INFO expected <block end>, but found FlowEntry 16.03 00:47:11 [Server] INFO in 'string', line 21, column 68: 16.03 00:47:11 [Server] INFO ... ongratulations! You have killed",\"color\":\"red\",\"extra\":[{\ ... 16.03 00:47:11 [Server] INFO ^ 16.03 00:47:11 [Server] INFO at org.yaml.snakeyaml.parser.ParserImpl$ParseBlockSequenceEntry.produce(ParserImpl.java:515) ~[spigot-1.12.2.jar:git-Spigot-9f4c3d2-bd30843]

Deleted whole files generate by plugin still this errror comes up.
Redownload the latest jar still can't

**Comment by 2008Choco** [comment] 2018-05-06 22:28
This is a known issue, duplicate of #10

**Closed as completed** 2018-05-06 22:29 UTC
Labels: bug, duplicate
