### ISSUE TITLE
error

### ISSUE THREAD

**Issue by ghost** [2008Choco/DragonEggDrop#6] opened 2017-09-20 18:06 UTC
log
```
[14:02:54] [Server thread/INFO]: [DragonEggDrop] Enabling DragonEggDrop v1.4.1
[14:02:54] [Server thread/ERROR]: Error occurred while enabling DragonEggDrop v1.4.1 (Is it up to date?)
java.lang.NullPointerException: null
	at com.ninjaguild.dragoneggdrop.DragonEggDrop.readTempData(DragonEggDrop.java:284) ~[?:?]
	at com.ninjaguild.dragoneggdrop.DragonEggDrop.onEnable(DragonEggDrop.java:140) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[patched_1.12.2.jar:git-Paper-1209]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:316) [patched_1.12.2.jar:git-Paper-1209]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:404) [patched_1.12.2.jar:git-Paper-1209]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:386) [patched_1.12.2.jar:git-Paper-1209]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:335) [patched_1.12.2.jar:git-Paper-1209]
	at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:442) [patched_1.12.2.jar:git-Paper-1209]
	at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:403) [patched_1.12.2.jar:git-Paper-1209]
	at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:341) [patched_1.12.2.jar:git-Paper-1209]
	at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:290) [patched_1.12.2.jar:git-Paper-1209]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:616) [patched_1.12.2.jar:git-Paper-1209]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
[14:02:54] [Server thread/INFO]: [DragonEggDrop] Disabling DragonEggDrop v1.4.1
```
timings
https://timings.aikar.co/?id=e4d1b2a619e34ecb8e99763214b6b962

**Comment by 2008Choco** [comment] 2017-09-22 17:38
Seems like a duplicate of #5. The issue has been fixed, I just have to find the time to finish up a release. Perhaps this weekend I will build a new version.

**Closed as completed by 2008Choco** 2017-09-22 17:38 UTC
Labels: duplicate
